---
kind: pipeline
type: docker
name: source-code-analysis-in-drone
      
platform:
  os: linux
  arch: amd64

steps:
  - name: source-code-analysis-branch
    pull: if-not-exists
    image: sonarsource/sonar-scanner-cli
    environment:
        SAST_SERVER_DRONE_WEB: 
          from_secret: sast_server
        SAST_TOKEN_DRONE_WEB:
          from_secret: sast_token
        SONAR_TOKEN: f55e2744c6dce02e2d90c413e3fbe894d3b946ee

    volumes:
      - name: cache
        path: ~/.sonar
    commands:
      - "sonar-scanner \
       -Dsonar.organization=jayenkim \
       -Dsonar.projectKey=BRANCH-${DRONE_REPO_NAMESPACE}_${DRONE_REPO_NAME}_${DRONE_COMMIT_AUTHOR} \
       -Dsonar.sources=. \
       -Dsonar.host.url=https://sonarcloud.io \
       -Dsonar.login=f55e2744c6dce02e2d90c413e3fbe894d3b946ee \
       -Dsonar.java.binaries=. \ 
       -Dsonar.java.libraries=. \
       -Dsonar.branch.name=main \ 
       -Dsonar.exclusions=*LICENSE* \  
       --debug" 
    when:
      event:
        include:
          - push

  - name: source-code-analysis-pr
    pull: if-not-exists
    image: sonarsource/sonar-scanner-cli
    environment:
        SAST_SERVER_DRONE_WEB: 
          from_secret: sast_server
        SAST_TOKEN_DRONE_WEB:
          from_secret: sast_token
    volumes:
      - name: cache
        path: ~/.sonar
    commands:
      - "sonar-scanner \
       -Dsonar.organization=jayenkim \
       -Dsonar.projectKey=${DRONE_REPO_NAMESPACE}_${DRONE_REPO_NAME} \
       -Dsonar.sources=. \
       -Dsonar.host.url=https://sonarcloud.io \
       -Dsonar.login=f55e2744c6dce02e2d90c413e3fbe894d3b946ee \
       -Dsonar.java.binaries=. \ 
       -Dsonar.java.libraries=. \
       -Dsonar.exclusions=*LICENSE* \  
       --debug" 
#       -Dsonar.issuesReport.console.enable=true \ 
#       -Dsonar.qulitygate.wait=true \   
#       -Dsonar.qualitygate.timeout=150 \
#        -Dsonar.branch.name=main \
    when:
      branch: 
        - main
      event:
        include:
          - pull_request
      ref:
        - refs/heads/master
        - refs/pull/**   